# ANN from Scratch - SUSY Dataset

Build a neural network from scratch using only NumPy to classify particle collision events as **Signal** or **Background** based on detector measurements.

## Tasks

1. **Load and inspect:** Explore `train_df` and `test_df` to understand the feature distributions, data types, class balance, and check for missing values.
2. **Preprocess:** Separate features and target, standardize the input features, and prepare the data for training.
3. **Build the ANN:** Implement a neural network from scratch using only NumPy, including weight initialization, forward propagation, loss computation, backpropagation, and parameter updates.
4. **Train:** Train the neural network by experimenting with suitable hyperparameters such as hidden layers, activation functions, learning rate, batch size, and number of epochs.
5. **Predict:** Generate predictions on `test_df` and store them in a NumPy array named `y_test_pred` containing only binary values (0 or 1).

In [2]:

import numpy as np
import pandas as pd
# from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the datasets
train_data = pd.read_csv("https://s3.ap-south-1.amazonaws.com/new-assets.ccbp.in/frontend/content/aiml/train.csv")
test_data = pd.read_csv("https://s3.ap-south-1.amazonaws.com/new-assets.ccbp.in/frontend/content/aiml/test.csv")

In [3]:
#Write your code here
train_data.head()

,target,lepton_1_pT,lepton_1_eta,lepton_1_phi,lepton_2_pT,lepton_2_eta,lepton_2_phi,missing_energy_magnitude,missing_energy_phi,MET_rel,axial_MET,M_R,M_TR_2,R,MT2,S_R,M_Delta_R,dPhi_r_b,cos_theta_r1
0,0.0,0.592842,-0.717434,-1.418097,0.925039,-1.167958,-0.232581,0.410790,0.946202,0.066825,-0.093145,0.621651,0.661949,0.944920,1.173945,0.613367,0.875812,0.312156,0.012921
1,1.0,0.813137,0.279405,0.712756,1.181922,0.513273,1.676590,1.474581,-0.095706,2.203669,-0.628283,0.800993,1.412994,1.565413,2.620315,0.871924,1.967665,1.091777,0.260520
2,1.0,1.647235,0.629698,-0.997650,1.976617,0.436282,0.477163,1.076584,1.255160,1.592031,-0.743501,1.484738,1.568309,0.937338,1.975349,1.521866,1.515855,1.363124,0.176546
3,0.0,0.437782,-0.262191,0.955048,0.529959,-1.256946,0.058239,0.485247,-1.001818,0.728415,-0.158763,0.466797,0.623313,1.184936,1.183245,0.470008,0.893762,0.864847,0.190235
4,0.0,0.422366,0.591228,0.164254,0.632580,0.739332,-1.090155,0.709699,1.463184,1.065345,-0.380906,0.419498,0.712362,1.506909,1.177480,0.477351,0.922684,1.478978,0.188495

In [4]:
test_data.head()

,lepton_1_pT,lepton_1_eta,lepton_1_phi,lepton_2_pT,lepton_2_eta,lepton_2_phi,missing_energy_magnitude,missing_energy_phi,MET_rel,axial_MET,M_R,M_TR_2,R,MT2,S_R,M_Delta_R,dPhi_r_b,cos_theta_r1
0,0.741761,1.444356,0.288903,0.469334,-0.497776,-1.544658,2.805451,-1.230771,2.222667,-2.400527,0.868910,1.617889,1.652299,0.759768,1.161935,2.197975,1.543306,0.484266
1,0.897132,1.309742,0.509178,0.934167,1.481388,-0.064917,1.342124,-1.466517,0.525125,-1.029448,0.764803,1.520600,1.764335,3.135562,0.817957,2.334983,1.403919,0.434683
2,0.413344,1.752021,0.646237,0.629387,0.964990,-0.878936,0.524679,1.047391,0.516491,0.175666,0.455412,0.524509,1.022030,0.498088,0.478648,0.425391,1.330516,0.220137
3,0.969497,0.617610,-0.178320,0.605191,1.279711,1.538937,1.294715,0.848291,1.851804,-0.015842,0.742186,1.103268,1.319120,0.000000,0.796804,1.061530,1.170463,0.389613
4,0.874558,-1.052374,1.461904,1.056917,-0.885959,0.903353,0.534368,0.260836,0.704688,0.209130,0.788918,0.773001,0.869491,1.358958,0.539463,1.125127,0.468827,0.411764

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   target                    8000 non-null   float64
 1   lepton_1_pT               8000 non-null   float64
 2   lepton_1_eta              8000 non-null   float64
 3   lepton_1_phi              8000 non-null   float64
 4   lepton_2_pT               8000 non-null   float64
 5   lepton_2_eta              8000 non-null   float64
 6   lepton_2_phi              8000 non-null   float64
 7   missing_energy_magnitude  8000 non-null   float64
 8   missing_energy_phi        8000 non-null   float64
 9   MET_rel                   8000 non-null   float64
 10  axial_MET                 8000 non-null   float64
 11  M_R                       8000 non-null   float64
 12  M_TR_2                    8000 non-null   float64
 13  R                         8000 non-null   float64
 14  MT2                       8000 non-null   float64
 15  S_R                       8000 non-null   float64
 16  M_Delta_R                 8000 non-null   float64
 17  dPhi_r_b                  8000 non-null   float64
 18  cos_theta_r1              8000 non-null   float64
dtypes: float64(19)
memory usage: 1.2 MB

In [6]:
train_data.describe()

,target,lepton_1_pT,lepton_1_eta,lepton_1_phi,lepton_2_pT,lepton_2_eta,lepton_2_phi,missing_energy_magnitude,missing_energy_phi,MET_rel,axial_MET,M_R,M_TR_2,R,MT2,S_R,M_Delta_R,dPhi_r_b,cos_theta_r1
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,0.457125,0.995016,-0.013348,0.003668,0.992268,-0.018616,0.017288,1.000720,-0.003247,0.991718,0.009587,0.999678,0.993887,0.996630,0.995447,0.997712,0.998567,0.998713,0.224263
std,0.498189,0.679606,1.003393,1.000649,0.638949,1.003093,0.999114,0.913232,1.005383,0.892387,1.042050,0.641752,0.584734,0.473029,0.845923,0.634647,0.623826,0.437193,0.198233
min,0.000000,0.265829,-2.102170,-1.733993,0.428710,-2.058400,-1.733843,0.002086,-1.726604,0.000276,-7.638416,0.286442,0.018059,0.025997,0.000000,0.155334,0.007738,0.001156,0.000016
25%,0.000000,0.560582,-0.770496,-0.862612,0.592997,-0.778232,-0.856845,0.482488,-0.876479,0.370425,-0.482362,0.588614,0.618320,0.649439,0.180703,0.595964,0.512043,0.683905,0.065453
50%,0.000000,0.786867,-0.010270,0.010979,0.800142,-0.015628,0.033274,0.769470,-0.017430,0.784282,-0.078495,0.828485,0.871908,0.931363,0.901472,0.836643,0.914616,1.091189,0.167696
75%,1.000000,1.203990,0.740257,0.868379,1.159585,0.752566,0.878354,1.186445,0.876298,1.363874,0.343483,1.200520,1.205039,1.277237,1.600456,1.195215,1.378777,1.369953,0.328589
max,1.000000,8.843125,2.101403,1.734187,8.567926,2.054770,1.734349,13.680408,1.740314,11.048742,13.375183,13.969072,6.523737,5.335464,4.128568,14.024200,5.267689,1.591462,0.953326

In [7]:
X = train_data.drop(columns=['target'])
y = train_data['target']

X = X.values
y = y.values.reshape(-1, 1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
scale = StandardScaler()
X_scaled = scale.fit_transform(x_train)
X_test_scaled = scale.transform(x_test)

In [9]:
def sigmoid(z):
  return 1/(1+np.exp(-z))
def relu(z):
  return np.maximum(0, z)
def relu_der(z):
  return (z>0).astype(float)
def tanh(z):
  return np.tanh(z)
def tanh_der(z):
  return 1- np.tanh(z)**2

In [10]:
# loss
def  compute_loss(y, y_pred):
  m = y.shape[0]
  epsilon = 1e-8
  y_pred = np.clip(y_pred, epsilon, 1-epsilon)
  return -(1/m)*np.sum(y*np.log(y_pred) + (1-y)*np.log(1-y_pred))

In [11]:
#base model with no hidden layers

n_features = X_scaled.shape[1]
W = np.random.randn(n_features, 1)*0.01
b = 0

In [12]:
def forward_no_hidden(X, W, b):
  z = np.dot(X, W) + b
  a = sigmoid(z)
  return a

def backward_np_hidden(X, y, y_hat):
  m = X.shape[0]
  dz = y_hat-y 
  dw = (1/m)*np.dot(X.T, dz)
  db = (1/m)*np.sum(dz)
  return dw, db

In [13]:
#train baseline model 
learning_rate = 0.5
epoches = 1000

losses_baseline = []

for epoch in range(epoches):
  y_hat = forward_no_hidden(X_scaled, W, b)
  loss = compute_loss(y_train, y_hat)
  losses_baseline.append(loss)

  dw, db = backward_np_hidden(X_scaled, y_train, y_hat)
  W -= learning_rate*dw
  b -= learning_rate*db

  if epoch%100 ==0:
    print(f"[Baseline] Epoch {epoch} | Loss: {loss:.4f}")

[Baseline] Epoch 0 | Loss: 0.6955
[Baseline] Epoch 100 | Loss: 0.4741
[Baseline] Epoch 200 | Loss: 0.4675
[Baseline] Epoch 300 | Loss: 0.4649
[Baseline] Epoch 400 | Loss: 0.4634
[Baseline] Epoch 500 | Loss: 0.4624
[Baseline] Epoch 600 | Loss: 0.4616
[Baseline] Epoch 700 | Loss: 0.4609
[Baseline] Epoch 800 | Loss: 0.4604
[Baseline] Epoch 900 | Loss: 0.4600

In [14]:
#baseline accuracy 
y_train_pred_base = (forward_no_hidden(X_scaled, W, b)[0]>=0.5).astype(int)
y_test_pred_base = (forward_no_hidden(X_test_scaled, W, b)[0]>=0.5).astype(int)

def compute_accuracy(y_true, y_pred):
  return np.mean(y_true==y_pred)

print("Baseline Training Accuracy:", compute_accuracy(y_train, y_train_pred_base))
print("Baseline Testing Accuracy:", compute_accuracy(y_test, y_test_pred_base))

Baseline Training Accuracy: 0.45765625
Baseline Testing Accuracy: 0.545

In [15]:
#With Hidden layers
np.random.seed(42)

input_neurons = X_scaled.shape[1]
hidden_neurons = 3
output_neurons =1

W1 = np.random.randn(input_neurons, hidden_neurons)*0.01
b1 = np.zeros((1, hidden_neurons))
W2 = np.random.randn(hidden_neurons, output_neurons)*0.01
b2 = np.zeros((1, output_neurons))

In [16]:
#forward propagation with hidden layers

def forward_hidden(X, W1, b1, W2, b2):
  z1 = np.dot(X, W1)+b1 
  a1 = tanh(z1)

  z2 = np.dot(a1, W2) + b2
  a2 = sigmoid(z2)

  return a2, z1, a1


def backward_hidden(X, y, a2, z1, a1, W2):
  m = X.shape[0]

  dz2 = a2-y
  dw2 = (1/m)*(np.dot(a1.T, dz2))
  db2 = (1/m)*np.sum(dz2, axis=0, keepdims =True)

  da1 = np.dot(dz2, W2.T)
  dz1 = da1*tanh_der(z1)
  dw1 = (1/m)*np.dot(X.T, dz1)
  db1 = (1/m)*np.sum(dz1, axis=0, keepdims=True)

  return dw1, db1, dw2, db2

In [17]:
#training model with hidden layers

learning_rate = 0.08
epoches = 1000
losses_hidden = []

for epoch in range(epoches):
  a2, z1, a1 = forward_hidden(X_scaled, W1, b1, W2, b2)
  loss = compute_loss(y_train, a2)
  losses_hidden.append(loss)

  dw1, db1, dw2, db2 = backward_hidden(X_scaled, y_train, a2, z1, a1, W2)

  W1 -= learning_rate*dw1
  b1 -= learning_rate*db1
  W2 -= learning_rate*dw2
  b2 -= learning_rate*db2

  if epoch%100==0:
    print(f"[Hidden layer] Epoch {epoch} | Loss {loss:.4f}")

[Hidden layer] Epoch 0 | Loss 0.6932
[Hidden layer] Epoch 100 | Loss 0.6748
[Hidden layer] Epoch 200 | Loss 0.5455
[Hidden layer] Epoch 300 | Loss 0.5012
[Hidden layer] Epoch 400 | Loss 0.4823
[Hidden layer] Epoch 500 | Loss 0.4717
[Hidden layer] Epoch 600 | Loss 0.4658
[Hidden layer] Epoch 700 | Loss 0.4623
[Hidden layer] Epoch 800 | Loss 0.4598
[Hidden layer] Epoch 900 | Loss 0.4581

In [18]:
y_train_pred_hidden = (forward_hidden(X_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)
y_test_pred_hidden = (forward_hidden(X_test_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)

print("Hidden layer Training Accuracy:", compute_accuracy(y_train, y_train_pred_hidden))
print("Hidden layer Testing Accuraccy:", compute_accuracy(y_test, y_test_pred_hidden))

Hidden layer Training Accuracy: 0.7903125
Hidden layer Testing Accuraccy: 0.78125

In [19]:
#Xavier weight Initialiation 

def xavier_init(fan_in, fan_out):
  return np.random.randn(fan_in, fan_out)*np.sqrt(1/fan_in)

W1 = xavier_init(input_neurons, hidden_neurons)
b1 = np.zeros((1, hidden_neurons))

W2 = xavier_init(hidden_neurons, output_neurons)
b2 = np.zeros((1, output_neurons))

In [20]:
#training after xavier

losses_xavier = []

for epoch in range(epoches):
  a2, z1, a1 = forward_hidden(X_scaled, W1, b1, W2, b2)
  loss = compute_loss(y_train, a2)
  losses_xavier.append(loss)

  dw1, db1, dw2, db2 = backward_hidden(X_scaled, y_train, a2, z1, a1, W2)

  W1 -= learning_rate*dw1
  b1 -= learning_rate*db1 
  W2 -= learning_rate*dw2 
  b2 -= learning_rate*db2

  if epoch%100==0:
    print(f"[Hidden-xavier] Epoch {epoch} | Loss {loss:.4f}")

[Hidden-xavier] Epoch 0 | Loss 0.8622
[Hidden-xavier] Epoch 100 | Loss 0.5292
[Hidden-xavier] Epoch 200 | Loss 0.4913
[Hidden-xavier] Epoch 300 | Loss 0.4762
[Hidden-xavier] Epoch 400 | Loss 0.4686
[Hidden-xavier] Epoch 500 | Loss 0.4645
[Hidden-xavier] Epoch 600 | Loss 0.4620
[Hidden-xavier] Epoch 700 | Loss 0.4602
[Hidden-xavier] Epoch 800 | Loss 0.4588
[Hidden-xavier] Epoch 900 | Loss 0.4576

In [21]:
y_train_pred_hidden_xavier = (forward_hidden(X_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)
y_test_pred_hidden_xavier = (forward_hidden(X_test_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)

print("Hidden-xavier layer Training Accuracy:", compute_accuracy(y_train, y_train_pred_hidden))
print("Hidden-xavier layer Testing Accuraccy:", compute_accuracy(y_test, y_test_pred_hidden))

Hidden-xavier layer Training Accuracy: 0.7903125
Hidden-xavier layer Testing Accuraccy: 0.78125

In [22]:
#applying mini-batch gradient descent

batch_size = 32
num_samples = X_scaled.shape[0]

for epoch in range(epoches):
    indices = np.random.permutation(num_samples)
    X_shuffled = X_scaled[indices]
    y_shuffled = y_train[indices]
    
    for start in range(0, num_samples, batch_size):
        end = start + batch_size
        X_batch = X_shuffled[start:end]
        y_batch = y_shuffled[start:end]
        
        a2, z1, a1 = forward_hidden(X_batch, W1, b1, W2, b2)
        dw1, db1, dw2, db2 = backward_hidden(X_batch, y_batch, a2, z1, a1, W2)
        
        W1 -= learning_rate * dw1
        b1 -= learning_rate * db1
        W2 -= learning_rate * dw2
        b2 -= learning_rate * db2
    
    if epoch%100==0:
        loss = compute_loss(y_train, forward_hidden(X_scaled, W1, b1, W2, b2)[0])
        print(f"[Hidden-Mini-batch] Epoch {epoch} | Loss {loss:.4f}")

[Hidden-Mini-batch] Epoch 0 | Loss 0.4594
[Hidden-Mini-batch] Epoch 100 | Loss 0.4355
[Hidden-Mini-batch] Epoch 200 | Loss 0.4328
[Hidden-Mini-batch] Epoch 300 | Loss 0.4345
[Hidden-Mini-batch] Epoch 400 | Loss 0.4364
[Hidden-Mini-batch] Epoch 500 | Loss 0.4335
[Hidden-Mini-batch] Epoch 600 | Loss 0.4325
[Hidden-Mini-batch] Epoch 700 | Loss 0.4320
[Hidden-Mini-batch] Epoch 800 | Loss 0.4319
[Hidden-Mini-batch] Epoch 900 | Loss 0.4320

In [23]:
y_train_pred_mb = (forward_hidden(X_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)
y_test_pred_mb = (forward_hidden(X_test_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)

print("Hidden-Mini-batch layer Training Accuracy:", compute_accuracy(y_train, y_train_pred_mb))
print("Hidden-Mini-batch layer Test Accuracy:", compute_accuracy(y_test, y_test_pred_mb))

Hidden-Mini-batch layer Training Accuracy: 0.80109375
Hidden-Mini-batch layer Test Accuracy: 0.78125

In [24]:
#Apply He initialization for relu activation function 

def he_init(fan_in, fan_out):
    return np.random.randn(fan_in, fan_out)*np.sqrt(2/fan_in)

W1 = he_init(input_neurons, hidden_neurons)
b1 = np.zeros((1, hidden_neurons))

W2 = he_init(hidden_neurons, output_neurons)
b2 = np.zeros((1, output_neurons))

In [25]:
losses_he = []

for epoch in range(epoches):
    indices = np.random.permutation(num_samples)
    X_shuffled = X_scaled[indices]
    y_shuffled = y_train[indices]
    
    for start in range(0, num_samples, batch_size):
        end = start + batch_size
        X_batch = X_shuffled[start:end]
        y_batch = y_shuffled[start:end]
        
        a2, z1, a1 = forward_hidden(X_batch, W1, b1, W2, b2)
        dw1, db1, dw2, db2 = backward_hidden(X_batch, y_batch, a2, z1, a1, W2)
        
        W1 -= learning_rate * dw1
        b1 -= learning_rate * db1
        W2 -= learning_rate * dw2
        b2 -= learning_rate * db2
    
    if epoch%100==0:
        loss = compute_loss(y_train, forward_hidden(X_scaled, W1, b1, W2, b2)[0])
        print(f"[Hidden-He] Epoch {epoch} | Loss {loss:.4f}")

[Hidden-He] Epoch 0 | Loss 0.5184
[Hidden-He] Epoch 100 | Loss 0.4455
[Hidden-He] Epoch 200 | Loss 0.4424
[Hidden-He] Epoch 300 | Loss 0.4415
[Hidden-He] Epoch 400 | Loss 0.4420
[Hidden-He] Epoch 500 | Loss 0.4419
[Hidden-He] Epoch 600 | Loss 0.4407
[Hidden-He] Epoch 700 | Loss 0.4420
[Hidden-He] Epoch 800 | Loss 0.4407
[Hidden-He] Epoch 900 | Loss 0.4426

In [26]:
x_train_pred_he_mb = (forward_hidden(X_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)
y_test_pred_he_mb = (forward_hidden(X_test_scaled, W1, b1, W2, b2)[0]>=0.5).astype(int)

print("Hidden-He layer Training Accuracy:", compute_accuracy(y_train, x_train_pred_he_mb))
print("Hidden-He layer Test Accuracy:", compute_accuracy(y_test, y_test_pred_he_mb))

Hidden-He layer Training Accuracy: 0.79703125
Hidden-He layer Test Accuracy: 0.7825